---

- name: Check if MySQL is already installed.
  ansible.builtin.stat:
    path: /etc/mysql/my.cnf
  register: mysql_installed

- name: Update apt cache if MySQL is not yet installed.
  ansible.builtin.apt:
    update_cache: yes
  changed_when: False
  when: not mysql_installed.stat.exists

- name: Install MySQL if not already installed
  ansible.builtin.apt:
    name: mysql-server
    state: present
  when: not mysql_installed.stat.exists

- name: Install MySQL Python libraries
  ansible.builtin.apt:
    name: python3-mysqldb
    state: present
  

